spring:
    application:
        name: ai-service
    data:
        mongodb:
            uri: ${MONGODB_URI:mongodb://localhost:27017/fitness_app}
    config:
        import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
    port: ${PORT:8080}
