server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivities
      database: fitnessactivities
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # This forces it to register as "localhost"
    hostname: localhost

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
